title: "Zach Metcalf"

remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
color_scheme: dark
# favicon_ico: "/data/icons/zmetcalf_icon0.ico"
favicon_ico: "/data/images/zmetcalf_icon0.png"

aux_links_new_tab: true
search_enabled: false

aux_links:
  "LinkedIn":
    - "https://www.linkedin.com/in/zachmetcalf/"
  "GitHub":
    - "https://github.com/zachmetcalf"

callouts:
  note:
    title: NOTE
    color: blue
  warn:
    title: WARNING
    color: yellow
  danger:
    title: DANGER
    color: red
