# Copyright (c) 2026 Zach Metcalf. All Rights Reserved.

name: Secrets

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    name: Check for leaks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
